# App configrations
version: "0.0.1"

app_name: 
  "Music Player"


# Assets configrations
assets_dir: 
  "assets"

assets_server_port: 
  8007

font_dir: 
  "fonts"


# Window configrations
Debug: 
  True

frameless: 
  True

maximixed: 
  True

fixed_size: 
  True

win_height: 
  600

win_width: 
  800


# Dependencies
dependencies: 
  "yaml"

